apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pandorahearts
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/TON_GITHUB/pandorahearts.git
    targetRevision: main
    path: deploy/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: pandorahearts
  syncPolicy:
    automated:
      prune: true
      selfHeal: true